#!/usr/bin/env tsx
import chalk from 'chalk';
import { writeFileSync } from 'node:fs';
import path from 'node:path';

import { getCollectionEntries, withAstroContent } from '../shared/astro-content.js';
import { findWorkspaceRoot } from '../shared/utils.js';
import { buildRedirectPairs, redirectCollections } from './build-redirect-pairs.js';

// WordPress permalinks the site no longer answers to, written by hand because no field records them
// Lists and designs became plain Posts; three taxonomies were renamed
// `/keywords/branding/` is deliberately absent: the term carried no posts, so its archive was empty
const structuralRedirects: Array<[string, string]> = [
	['/lists/*', '/:splat'],
	['/designs/*', '/:splat'],
	['/projects/*', '/artists/:splat'],
	['/time-periods/*', '/eras/:splat'],
	// Archive indexes, both linked from the WordPress main nav; exact rules beat the wildcards above
	['/lists/', '/formats/selections/'],
	['/designs/', '/formats/album-artwork/'],
	// WordPress served Pages under their parent; resonance serves every Page at the site root
	['/about/frequently-asked-questions/', '/frequently-asked-questions/'],
	['/about/privacy-policy/', '/privacy-policy/'],
	['/profile/booking/', '/booking/'],
	['/resources/command-line-tools/', '/command-line-tools/'],
	['/resources/jriver-media-center-user-guide/', '/jriver-media-center-user-guide/'],
	[
		'/resources/verifying-lossless-audio-quality-with-spectral-analysis/',
		'/verifying-lossless-audio-quality-with-spectral-analysis/',
	],
	// `page_on_front`, which WordPress answered at the site root and redirected the slug to
	['/sounds-from-the-great-beyond/', '/'],
	// The `best-mixes` term was dropped on purpose; its 19 mixes are still the nearest surface
	['/keywords/best-mixes/', '/mixes/'],
	// The SEO Framework served the sitemap here
	['/sitemap.xml', '/sitemap-index.xml'],
	['/sections/articles/', '/formats/articles/'],
	['/sections/notes/', '/formats/notes/'],
	['/sections/quotations/', '/formats/quotations/'],
	['/sections/tracks/', '/formats/tracks/'],
	['/keywords/album-artwork/', '/formats/album-artwork/'],
	['/sections/meta/', '/themes/meta/'],
	['/keywords/interviews/', '/themes/interviews/'],
	['/keywords/music-strategy/', '/themes/music-strategy/'],
	['/keywords/musicology/', '/themes/musicology/'],
	['/keywords/physical-media/', '/themes/physical-media/'],
	['/keywords/toolkit/', '/themes/toolkit/'],
	// WordPress served a feed at every permalink
	// A Cloudflare splat only sits at the end of a rule, so the per-entry ones are placeholders
	['/feed/', '/rss.xml'],
	['/:slug/feed/', '/rss.xml'],
	['/:section/:slug/feed/', '/rss.xml'],
	// The upload tree is served off the file server rather than the Worker: 5,229 of the 5,876
	// referenced paths are `-WxH` srcset derivatives, and 1.3 GB has no place in every version
	['/wp-content/uploads/*', 'https://files.djbasilisk.com/uploads/:splat'],
];

const rootPath = findWorkspaceRoot();

const entries = await withAstroContent((content) =>
	getCollectionEntries(content, [...redirectCollections]),
);

const { collisions, pairs, skipped } = buildRedirectPairs(entries);

// Writing the file anyway would ship a rule that takes a live page off the site
if (collisions.length > 0) {
	for (const collision of collisions) {
		console.error(chalk.red(`✗ former id collision: ${collision}`));
	}

	process.exit(1);
}

// A placeholder is dynamic just as a splat is, so both sort below the exact rules
function isDynamic(from: string) {
	return from.includes('*') || from.includes(':');
}

const structuralExact = structuralRedirects.filter(([from]) => !isDynamic(from));
const structuralDynamic = structuralRedirects.filter(([from]) => isDynamic(from));

const lines = [
	'# Generated by `pnpm generate-redirects`; do not edit',
	'',
	'# Structural moves off WordPress, hand-written in generate-redirects/index.ts',
	...structuralExact.map(([from, to]) => `${from} ${to} 301`),
	'',
	'# Generated from `formerIds`',
	...pairs.map(({ from, to }) => `${from} ${to} 301`),
	'',
	'# Dynamic rules last: Cloudflare counts every rule below one as dynamic, and allows 100',
	...structuralDynamic.map(([from, to]) => `${from} ${to} 301`),
	'',
];

// Cloudflare serves `_redirects` from the assets directory, which is where `public/` lands
const outputFile = 'public/_redirects';

writeFileSync(path.resolve(rootPath, outputFile), lines.join('\n'));

for (const note of skipped) {
	console.log(chalk.yellow(`⚠️  skipped ${note}`));
}

console.log(
	chalk.green(
		`✓ ${structuralRedirects.length.toString()} structural and ${pairs.length.toString()} generated redirects → ${outputFile}`,
	),
);
