import type { CollectionKey } from 'astro:content';

import {
	OPEN_GRAPH_BASE_PATH,
	OPEN_GRAPH_DEFAULT_ID,
	OPEN_GRAPH_IMAGE_FORMAT,
} from '@xsynaptic/shared/constants';
import { OG_BASE_URL } from 'astro:env/server';

// Cards are generated by `pnpm og-image` into the same filename stem
export function getOpenGraphId(collection: CollectionKey, id: string): string {
	return `${collection}-${id}`;
}

/**
 * Cards sit on the site's own origin today. `OG_BASE_URL` is the seam for moving them somewhere
 * durable, which is what a rename needs; see `.claude/tasks-backlog/00-backlog.md` under
 * "Durable home for OG images".
 */
export function getOpenGraphImageUrl(
	openGraphId: string | undefined,
	site: undefined | URL,
): string {
	const filename = `${openGraphId ?? OPEN_GRAPH_DEFAULT_ID}.${OPEN_GRAPH_IMAGE_FORMAT}`;

	return new URL(`${OPEN_GRAPH_BASE_PATH}/${filename}`, OG_BASE_URL ?? site).href;
}
