import type { PlayerLabels } from '#types.ts';

export const labels = {
	capped: 'Daily limit reached',
	clearQueue: 'Clear',
	close: 'Close',
	empty: 'Queue is empty',
	error: 'Playback error',
	expand: 'Expand',
	lists: 'Tracklist and Playlist',
	loading: 'Loading',
	moved: 'Moved to position {position} of {total}',
	mute: 'Mute',
	next: 'Next',
	nowPlaying: 'Nothing playing',
	pause: 'Pause',
	play: 'Play',
	playlist: 'Playlist',
	previous: 'Previous',
	queue: 'Queue',
	removeFromQueue: 'Remove',
	reorder: 'Reorder',
	seek: 'Seek',
	seekBack: 'Back 30 seconds',
	seekForward: 'Forward 30 seconds',
	seekPosition: '{current} of {duration}',
	shuffle: 'Shuffle',
	timestampsPartial: 'Timestamps end here',
	toggleTimeMode: 'Toggle elapsed and remaining',
	tracklist: 'Tracklist',
	unmute: 'Unmute',
	unplayable: 'This browser cannot play the stream',
	volume: 'Volume',
	waveformPanel: 'Waveform detail',
	zoomIn: 'Zoom in',
	zoomOut: 'Zoom out',
} satisfies PlayerLabels;
