import chalk from 'chalk';
import { createHash } from 'node:crypto';
import fs from 'node:fs/promises';
import path from 'node:path';

import { isPathPresent } from '../shared/utils.js';
import { convertCommentBody, findResidualMarkup } from './comment-body.js';

const taipeiOffsetSeconds = 8 * 60 * 60;

// Basilisk's comments are the persona's; WordPress had switched to the account address by 2019
const basiliskAccountEmail = 'alexander@synapticism.com';
const basiliskPersonaEmail = 'basilisk@ektoplazm.com';

interface EntryMapping {
	collection: string;
	commentStatus: string;
	postStatus: string;
	slug: string;
}

interface EntryReport extends EntryMapping {
	commentCount: number;
	filePath: string | undefined;
	postId: number;
}

interface ImportLegacyOptions {
	rootPath: string;
}

interface ImportResult {
	reports: Map<number, EntryReport>;
	residual: Array<string>;
	statements: Array<string>;
	unresolved: Map<number, number>;
}

interface LegacyComment {
	comment_approved: string;
	comment_author: string;
	comment_author_email: string;
	comment_author_url: string;
	comment_content: string;
	comment_date: string;
	comment_date_gmt: string;
	comment_ID: number;
	comment_parent: number;
	comment_post_ID: number;
}

export async function importLegacyComments(options: ImportLegacyOptions): Promise<void> {
	const { rootPath } = options;

	const contentPath = path.join(rootPath, 'packages', 'content');
	const archivePath = path.join(contentPath, 'archive');

	const archive = JSON.parse(
		await fs.readFile(path.join(archivePath, 'comments.json'), 'utf8'),
	) as {
		comments: Array<LegacyComment>;
	};

	const mapPath = path.join(archivePath, 'comment-entry-map.json');

	if (!(await isPathPresent(mapPath))) {
		throw new Error(
			`${mapPath} not found. Run \`pnpm -F @xsynaptic/scripts comments-map\` first; it needs the WordPress dump.`,
		);
	}

	const entryMap = JSON.parse(await fs.readFile(mapPath, 'utf8')) as {
		entries: Record<string, EntryMapping>;
	};

	const approved = archive.comments.filter((comment) => comment.comment_approved === '1');
	const fileIndex = await indexCollectionFiles(path.join(contentPath, 'collections'));
	const result = collectImport(approved, entryMap.entries, fileIndex);

	const seedPath = path.join(archivePath, 'comments-seed.sql');
	const reportPath = path.join(archivePath, 'comments-entries.md');

	await fs.writeFile(seedPath, `${result.statements.join('\n')}\n`);
	await fs.writeFile(reportPath, formatReport([...result.reports.values()]));

	printSummary(result, approved.length, seedPath, reportPath);
}

function buildInsert(comment: LegacyComment, mapping: EntryMapping): string {
	const email = toAuthorEmail(comment.comment_author_email);
	const url = comment.comment_author_url.trim();
	const parent = comment.comment_parent;

	const values = [
		sqlString(`wp-${String(comment.comment_ID)}`),
		sqlString(mapping.collection),
		sqlString(mapping.slug),
		parent > 0 ? sqlString(`wp-${String(parent)}`) : 'NULL',
		sqlString(comment.comment_author.trim()),
		email === '' ? 'NULL' : sqlString(email),
		url === '' ? 'NULL' : sqlString(url),
		email === '' ? 'NULL' : sqlString(gravatarHash(email)),
		sqlString(convertCommentBody(comment.comment_content)),
		sqlString('approved'),
		sqlString('wordpress'),
		String(toCreatedAt(comment)),
		'NULL',
		String(comment.comment_post_ID),
	];

	return `INSERT OR REPLACE INTO comments (id, collection, entry_id, parent_id, author, author_email, author_url, gravatar_hash, body, status, source, created_at, ip_hash, wp_post_id) VALUES (${values.join(', ')});`;
}

function collectImport(
	approved: Array<LegacyComment>,
	entries: Record<string, EntryMapping>,
	fileIndex: Map<string, string>,
): ImportResult {
	const result: ImportResult = {
		reports: new Map<number, EntryReport>(),
		residual: [],
		statements: [],
		unresolved: new Map<number, number>(),
	};

	for (const comment of approved) {
		const postId = comment.comment_post_ID;
		const mapping = entries[String(postId)];

		if (mapping === undefined) {
			result.unresolved.set(postId, (result.unresolved.get(postId) ?? 0) + 1);
			continue;
		}

		const leftovers = findResidualMarkup(convertCommentBody(comment.comment_content));

		if (leftovers.length > 0) {
			result.residual.push(`wp-${String(comment.comment_ID)}: ${leftovers.join(' ')}`);
		}

		result.statements.push(buildInsert(comment, mapping));

		const existing = result.reports.get(postId);

		if (existing) {
			existing.commentCount += 1;
			continue;
		}

		result.reports.set(postId, {
			...mapping,
			commentCount: 1,
			filePath: fileIndex.get(`${mapping.collection}/${mapping.slug}`),
			postId,
		});
	}

	return result;
}

function formatReport(reports: Array<EntryReport>): string {
	const closed = reports.filter((report) => report.commentStatus !== 'open');
	const drafts = reports.filter((report) => report.postStatus !== 'publish');

	const lines = [
		'# Legacy comment entries',
		'',
		'Generated by `pnpm comments-import`. One row per WordPress post carrying approved comments.',
		'',
		`- ${String(reports.length)} entries`,
		`- ${String(closed.length)} had comments closed in WordPress, so the extractor should emit \`commentsEnabled: false\` for them`,
		`- ${String(drafts.length)} are drafts today, so their comments sit in D1 unrendered until the entry publishes`,
		'',
		'| Entry | Comments | WP status | WP comments | File |',
		'| --- | --- | --- | --- | --- |',
	];

	const sorted = [...reports].sort((left, right) => left.slug.localeCompare(right.slug));

	for (const report of sorted) {
		const file = report.filePath === undefined ? '**missing**' : path.basename(report.filePath);

		lines.push(
			`| ${report.collection}/${report.slug} | ${String(report.commentCount)} | ${report.postStatus} | ${report.commentStatus} | ${file} |`,
		);
	}

	return `${lines.join('\n')}\n`;
}

// Raw addresses live in D1 alone; the build reads gravatar_hash, never author_email
function gravatarHash(email: string): string {
	return createHash('sha256').update(email.trim().toLowerCase()).digest('hex');
}

// The collection directories nest entries by year, and a draft carries a leading underscore
async function indexCollectionFiles(collectionsPath: string): Promise<Map<string, string>> {
	const index = new Map<string, string>();
	const collections = await fs.readdir(collectionsPath, { withFileTypes: true });

	for (const collection of collections) {
		if (!collection.isDirectory()) continue;

		const collectionPath = path.join(collectionsPath, collection.name);
		const entries = await fs.readdir(collectionPath, { recursive: true });
		const files = entries.filter((entry) => entry.endsWith('.mdx'));

		for (const file of files) {
			const slug = path.basename(file, '.mdx').replace(/^_/, '');

			index.set(`${collection.name}/${slug}`, path.join(collectionPath, file));
		}
	}

	return index;
}

function printSummary(
	result: ImportResult,
	approvedCount: number,
	seedPath: string,
	reportPath: string,
): void {
	console.log(chalk.blue('Legacy comment import'));
	console.log(chalk.gray(`  Approved comments: ${String(approvedCount)}`));
	console.log(chalk.gray(`  Entries:           ${String(result.reports.size)}`));
	console.log(chalk.gray(`  Statements:        ${String(result.statements.length)}`));
	console.log(chalk.gray(`  Seed:              ${seedPath}`));
	console.log(chalk.gray(`  Report:            ${reportPath}`));

	const missing = [...result.reports.values()].filter((report) => report.filePath === undefined);

	if (missing.length > 0) {
		console.log(chalk.yellow(`  ${String(missing.length)} entries resolve to no file:`));
		for (const report of missing) {
			console.log(
				chalk.yellow(`    ${report.collection}/${report.slug} (wp ${String(report.postId)})`),
			);
		}
	}

	if (result.unresolved.size > 0) {
		console.log(
			chalk.yellow(`  ${String(result.unresolved.size)} post ids absent from the entry map:`),
		);
		for (const [postId, count] of result.unresolved) {
			console.log(
				chalk.yellow(`    wp ${String(postId)} (${String(count)} comments, not imported)`),
			);
		}
	}

	if (result.residual.length > 0) {
		console.log(chalk.red(`  ${String(result.residual.length)} bodies still carry markup:`));
		for (const line of result.residual) console.log(chalk.red(`    ${line}`));
	}
}

function sqlString(value: null | string): string {
	if (value === null) return 'NULL';

	return `'${value.replaceAll("'", "''")}'`;
}

// Only Basilisk's own rows carry the account address, and they are his under either one
function toAuthorEmail(value: string): string {
	const email = value.trim();

	return email === basiliskAccountEmail ? basiliskPersonaEmail : email;
}

// WordPress wrote site-local time into the GMT column after the move to Taipei, `gmt_offset`
// having been left empty; local == GMT identifies those rows exactly, and a date window does not
function toCreatedAt(comment: LegacyComment): number {
	const seconds = toEpochSeconds(comment.comment_date_gmt);

	if (comment.comment_date !== comment.comment_date_gmt) return seconds;

	return seconds - taipeiOffsetSeconds;
}

function toEpochSeconds(value: string): number {
	const parsed = Date.parse(`${value.replace(' ', 'T')}Z`);

	if (Number.isNaN(parsed)) throw new Error(`Unparseable comment date: ${value}`);

	return Math.floor(parsed / 1000);
}
